import { KneeCoAppShell } from "@/components/KneeCoAppShell";
import { Button } from "@/components/ui/button";
import { getIllustrativeCase, kneeAnalysisPath } from "@/lib/caseArchive";
import { persistedCaseToWorkspaceCase } from "@/lib/persistedCase";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, ArrowUpRight, CheckCircle2, ClipboardList, ImageIcon, Stethoscope } from "lucide-react";
import { toast } from "sonner";
import { useLocation, useRoute } from "wouter";

function ProgressState({ title, detail, state }: { title: string; detail: string; state: "complete" | "current" | "idle" }) {
  const tone = state === "complete" ? "bg-[#E8F4EF] text-[#2D7A58]" : state === "current" ? "bg-[#F8E7EB] text-[#A6556A]" : "bg-[#F1EDF7] text-[#76568A]";
  return <div className="flex gap-4"><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full ${tone}`}>{state === "complete" ? <CheckCircle2 className="h-5 w-5" /> : <span className="text-xs font-extrabold">{state === "current" ? "02" : "03"}</span>}</span><div className="pb-6"><p className="text-sm font-extrabold text-[#48383F]">{title}</p><p className="mt-1 text-sm leading-6 text-[#7B676E]">{detail}</p></div></div>;
}

export default function CaseDetail() {
  const [, setLocation] = useLocation();
  const [, params] = useRoute("/cases/:caseId");
  const storedCase = trpc.cases.get.useQuery({ caseReference: params?.caseId ?? "unavailable" });
  const record = storedCase.data ? persistedCaseToWorkspaceCase(storedCase.data) : getIllustrativeCase(params?.caseId);
  const serviceStatus = trpc.analysis.serviceStatus.useQuery();
  const analysisStatusLabel = serviceStatus.isLoading ? "Checking service" : serviceStatus.data?.state === "validated" ? "Controlled validation" : "Awaiting validated model";
  const analysisStatusDetail = serviceStatus.data?.safeMessage ?? "The FastAPI analysis-service status is being checked.";

  return (
    <KneeCoAppShell eyebrow="Clinical case" title="Case Detail">
      <div className="mx-auto max-w-6xl">
        <button type="button" onClick={() => setLocation("/cases")} className="mb-5 inline-flex items-center text-sm font-extrabold text-[#8A5563] transition hover:text-[#733963]"><ArrowLeft className="mr-2 h-4 w-4" />Back to Case Overview</button>
        <section className="rounded-[1.75rem] border border-[#EFE4E6] bg-white p-7 shadow-[0_18px_45px_-35px_rgba(92,49,61,0.35)] sm:p-9"><div className="flex flex-col gap-6 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.17em] text-[#A6556A]">Active assessment</p><h2 className="font-kneeco-display mt-3 text-4xl tracking-[-0.04em] text-[#352C30]">Case {record.id}</h2><p className="mt-3 text-sm leading-6 text-[#7A676E]">{record.patientLabel} · {record.age} years · {record.sex} · {record.kneeSide} knee</p></div><div className="flex flex-wrap gap-3"><span className="rounded-full bg-[#F8E7EB] px-3 py-2 text-xs font-extrabold text-[#934F60]">{analysisStatusLabel}</span><Button type="button" onClick={() => setLocation("/new-case")} className="rounded-xl bg-[#C97C8D] text-white hover:bg-[#A6556A]">New Case</Button></div></div>
          <div className="mt-8 grid gap-4 sm:grid-cols-4"><div className="rounded-xl border border-[#EEE3E5] p-4"><p className="text-[10px] font-extrabold uppercase tracking-[0.13em] text-[#9C858C]">Patient</p><p className="mt-2 text-sm font-extrabold text-[#45353B]">{record.patientLabel}</p></div><div className="rounded-xl border border-[#EEE3E5] p-4"><p className="text-[10px] font-extrabold uppercase tracking-[0.13em] text-[#9C858C]">OA status</p><p className="mt-2 text-sm font-extrabold text-[#45353B]">{record.oaStatus}</p></div><div className="rounded-xl border border-[#EEE3E5] p-4"><p className="text-[10px] font-extrabold uppercase tracking-[0.13em] text-[#9C858C]">MRI study</p><p className="mt-2 text-sm font-extrabold text-[#45353B]">Uploaded</p></div><div className="rounded-xl border border-[#EEE3E5] p-4"><p className="text-[10px] font-extrabold uppercase tracking-[0.13em] text-[#9C858C]">Report</p><p className="mt-2 text-sm font-extrabold text-[#45353B]">{record.status === "report_signed" ? "Signed" : "Pending approval"}</p></div></div>
        </section>
        <section className="mt-7 grid gap-7 lg:grid-cols-[.95fr_1.05fr]"><div className="rounded-[1.6rem] border border-[#EDE3E5] bg-white p-6 shadow-[0_18px_45px_-38px_rgba(92,49,61,0.38)]"><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-[#A6556A]">Assessment pathway</p><h3 className="mt-2 text-xl font-extrabold text-[#3E3036]">Case progress</h3><div className="mt-7"><ProgressState title="Clinical intake" detail="Patient context and image/PDF knee study have been recorded." state="complete" /><ProgressState title="Knee assessment" detail={analysisStatusDetail} state="current" /><ProgressState title="Implant planning" detail="Not initiated. Start only when a clinician supplies verified dimensions and chooses to plan candidates." state="idle" /><ProgressState title="Final report" detail="Becomes available after the assessment is reviewed and approved." state="idle" /></div></div>
          <div className="space-y-7"><section className="rounded-[1.6rem] border border-[#EDE3E5] bg-white p-6 shadow-[0_18px_45px_-38px_rgba(92,49,61,0.38)]"><div className="flex items-start justify-between gap-5"><div><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-[#A6556A]">Knee assessment</p><h3 className="mt-2 text-xl font-extrabold text-[#3E3036]">Review the analysis</h3><p className="mt-2 text-sm leading-6 text-[#7B676E]">Open the MRI view, technical preflight state, future anatomical measurements, and clinical context for this case.</p></div><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#F8E7EB] text-[#A6556A]"><ImageIcon className="h-5 w-5" /></span></div><div className="mt-6 grid grid-cols-3 gap-3"><div className="rounded-xl bg-[#FFFAFB] p-3"><p className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-[#9B858B]">Femur</p><p className="mt-2 text-sm font-extrabold text-[#493940]">Not run</p></div><div className="rounded-xl bg-[#FFFAFB] p-3"><p className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-[#9B858B]">Tibia</p><p className="mt-2 text-sm font-extrabold text-[#493940]">Not run</p></div><div className="rounded-xl bg-[#FFFAFB] p-3"><p className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-[#9B858B]">Meniscus</p><p className="mt-2 text-sm font-extrabold text-[#493940]">Pending model</p></div></div>{record.oaClassifierResult && <div className="mt-5 rounded-xl border border-[#E8D6DA] bg-[#FFF9FA] p-4"><p className="text-[10px] font-extrabold uppercase tracking-[0.13em] text-[#A6556A]">OA image-classifier result · review only</p><div className="mt-2 flex flex-wrap items-end justify-between gap-3"><div><p className="text-lg font-extrabold text-[#493940]">{record.oaClassifierResult.stageLabel}</p><p className="mt-1 text-xs leading-5 text-[#7D6870]">Top class probability {(record.oaClassifierResult.topClassProbability * 100).toFixed(1)}% · {record.oaClassifierResult.modelName} · {record.oaClassifierResult.modelVersion}</p></div><span className="rounded-full bg-[#F7E4E8] px-3 py-1.5 text-xs font-extrabold text-[#965263]">Clinician review required</span></div><p className="mt-3 text-xs leading-5 text-[#806C73]">This model output is not a diagnosis and does not provide anatomy segmentation, meniscus thickness, or implant sizing.</p></div>}<Button type="button" onClick={() => setLocation(kneeAnalysisPath(record.id))} className="mt-6 rounded-xl bg-[#C97C8D] text-white hover:bg-[#A6556A]">Open Knee Analysis<ArrowUpRight className="ml-2 h-4 w-4" /></Button></section>
            {record.geminiReportState && <section className="rounded-[1.6rem] border border-[#DDE4EF] bg-[#FAFCFF] p-6"><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-[#596F9A]">Gemini report extraction</p><h3 className="mt-2 text-xl font-extrabold text-[#35445E]">{record.geminiReportState.status === "extracted_for_review" ? "Report findings ready for review" : record.geminiReportState.status === "not_a_report" ? "No readable radiology report found" : record.geminiReportState.status === "failed" ? "Report extraction could not complete" : "Report extraction is not configured"}</h3><p className="mt-2 text-sm leading-6 text-[#64738B]">{record.geminiReportState.message}</p><Button type="button" onClick={() => setLocation(kneeAnalysisPath(record.id))} variant="outline" className="mt-5 rounded-xl border-[#C8D5EA] bg-white text-[#536A95] hover:bg-[#F4F7FC]">Review report extraction<ArrowUpRight className="ml-2 h-4 w-4" /></Button></section>}
            <section className="rounded-[1.6rem] border border-[#EDE3E5] bg-[#FFF9FA] p-6"><div className="flex items-start justify-between gap-5"><div><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-[#A6556A]">Conditional planning</p><h3 className="mt-2 text-xl font-extrabold text-[#3E3036]">Implant planning</h3><p className="mt-2 text-sm leading-6 text-[#7B676E]">Initiate only when the clinician decides that candidate sizing support is appropriate.</p></div><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#733963] text-white"><ClipboardList className="h-5 w-5" /></span></div><Button type="button" onClick={() => toast.info("Implant planning will use the future FastAPI measurement output and implant catalogue.")} variant="outline" className="mt-6 rounded-xl border-[#D8BBC2] bg-white text-[#834959] hover:bg-[#FFF5F6]">Start Implant Planning<ArrowUpRight className="ml-2 h-4 w-4" /></Button></section>
            <section className="rounded-[1.6rem] border border-[#EDE3E5] bg-white p-5 text-sm text-[#765F67]"><span className="flex gap-3"><Stethoscope className="mt-0.5 h-5 w-5 shrink-0 text-[#A6556A]" />KneeCo provides clinical decision support only. Measurements and implant candidates require clinician review and do not replace diagnosis or surgical judgment.</span></section>
          </div></section>
      </div>
    </KneeCoAppShell>
  );
}
