import { KneeCoAppShell } from "@/components/KneeCoAppShell";
import { Button } from "@/components/ui/button";
import { getIllustrativeCase, type IllustrativeCase } from "@/lib/caseArchive";
import { persistedCaseToWorkspaceCase } from "@/lib/persistedCase";
import { trpc } from "@/lib/trpc";
import {
  ArrowLeft,
  CheckCircle2,
  CircleAlert,
  EyeOff,
  FileImage,
  Maximize2,
  Minus,
  Move,
  Plus,
  RotateCcw,
  ShieldCheck,
  Sparkles,
  Upload,
  UsersRound,
} from "lucide-react";
import { useState } from "react";
import { useLocation, useRoute } from "wouter";

type AnalysisTab = "mri" | "measurements" | "context";

const tabs: Array<{ id: AnalysisTab; label: string }> = [
  { id: "mri", label: "MRI View" },
  { id: "measurements", label: "Analysis" },
  { id: "context", label: "Clinical Context" },
];

function ToggleRow({ label, tone }: { label: string; tone: "femur" | "meniscus" | "tibia" }) {
  const colors = { femur: "bg-[#C97C8D]", meniscus: "bg-[#B4866D]", tibia: "bg-[#766094]" };
  return <div className="flex w-full items-center justify-between rounded-xl border border-[#EEE3E5] bg-white px-3 py-2.5 opacity-60"><span className="flex items-center gap-2.5 text-sm font-extrabold text-[#58454C]"><span className={`h-2.5 w-2.5 rounded-full ${colors[tone]}`} />{label}</span><EyeOff className="h-4 w-4 text-[#AC989E]" /></div>;
}

function SourceStudyPanel({ study, onCreateCase }: { study: IllustrativeCase["sourceStudy"]; onCreateCase: () => void }) {
  if (study?.mimeType.startsWith("image/")) {
    return <div className="overflow-hidden rounded-[1.5rem] border border-[#EAE0E2] bg-[#F8F5F6]"><div className="flex items-center justify-between border-b border-[#EAE0E2] bg-white px-4 py-3"><span className="flex items-center gap-2 text-xs font-extrabold text-[#634B53]"><FileImage className="h-4 w-4 text-[#A6556A]" />{study.fileName}</span><span className="rounded-full bg-[#F8E7EB] px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-[0.11em] text-[#995969]">Source study</span></div><div className="flex min-h-[320px] items-center justify-center p-4 sm:min-h-[460px]"><img src={study.url} alt={`Uploaded knee study: ${study.fileName}`} className="max-h-[440px] w-auto max-w-full rounded-xl object-contain shadow-[0_12px_32px_-22px_rgba(58,42,48,.5)]" /></div><p className="border-t border-[#EAE0E2] bg-white px-4 py-3 text-xs leading-5 text-[#806C73]">Source image only. Structure overlays are unavailable because the current model does not contain segmentation masks.</p></div>;
  }
  if (study?.mimeType === "application/pdf") {
    return <div className="overflow-hidden rounded-[1.5rem] border border-[#EAE0E2] bg-white"><div className="flex items-center justify-between border-b border-[#EAE0E2] px-4 py-3"><span className="flex items-center gap-2 text-xs font-extrabold text-[#634B53]"><FileImage className="h-4 w-4 text-[#A6556A]" />{study.fileName}</span><span className="rounded-full bg-[#F8E7EB] px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-[0.11em] text-[#995969]">PDF source</span></div><iframe title={`Uploaded knee study: ${study.fileName}`} src={study.url} className="h-[460px] w-full bg-[#F8F5F6]" /><p className="border-t border-[#EAE0E2] px-4 py-3 text-xs leading-5 text-[#806C73]">PDF source only. Structure overlays are unavailable because the current model does not contain segmentation masks.</p></div>;
  }
  return <div className="flex min-h-[280px] flex-col items-center justify-center rounded-[1.5rem] border border-dashed border-[#DEC9CE] bg-[#FFFAFB] p-8 text-center sm:min-h-[360px]"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#F7E5E9] text-[#A6556A]"><FileImage className="h-6 w-6" /></span><h4 className="mt-4 text-base font-extrabold text-[#493940]">No source study attached to this case</h4><p className="mt-2 max-w-sm text-sm leading-6 text-[#806C73]">This record does not include an image or PDF preview. Create a case with a knee study to review the source file here.</p><Button type="button" onClick={onCreateCase} className="mt-5 rounded-xl bg-[#C97C8D] text-white hover:bg-[#A6556A]"><Upload className="mr-2 h-4 w-4" />Add a knee study</Button></div>;
}

function OaClassifierResult({ result }: { result: IllustrativeCase["oaClassifierResult"] }) {
  if (!result) {
    return <section className="rounded-[1.6rem] border border-[#EDE3E5] bg-white p-6 shadow-[0_18px_45px_-38px_rgba(92,49,61,0.38)]"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#F8E7EB] text-[#A6556A]"><Sparkles className="h-5 w-5" /></span><div><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-[#A6556A]">Current model output</p><h3 className="mt-1 text-lg font-extrabold text-[#3E3036]">OA classifier has not run for this case</h3><p className="mt-2 text-sm leading-6 text-[#806C73]">Attach a supported knee image or PDF and run it through the configured FastAPI service to obtain the classifier’s four-stage probability output.</p></div></div></section>;
  }
  const classProbabilities = Object.entries(result.stageProbabilities ?? {});
  return <section className="rounded-[1.6rem] border border-[#E7D7DB] bg-[#FFF9FA] p-6 shadow-[0_18px_45px_-38px_rgba(92,49,61,0.38)]"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-[#A6556A]">OA image-classifier result · review only</p><h3 className="mt-2 text-2xl font-extrabold text-[#493940]">{result.stageLabel}</h3><p className="mt-1 text-sm text-[#806C73]">Top class probability {(result.topClassProbability * 100).toFixed(1)}% · {result.modelName} · {result.modelVersion}</p></div><span className="w-fit rounded-full bg-[#F7E4E8] px-3 py-1.5 text-xs font-extrabold text-[#965263]">Clinician review required</span></div><div className="mt-6 space-y-3">{classProbabilities.map(([label, probability]) => <div key={label}><div className="flex items-center justify-between text-xs font-extrabold text-[#6E5960]"><span>{label}</span><span>{(probability * 100).toFixed(1)}%</span></div><div className="mt-1.5 h-2 overflow-hidden rounded-full bg-[#F1E4E7]"><div className="h-full rounded-full bg-[#C97C8D]" style={{ width: `${Math.max(0, Math.min(100, probability * 100))}%` }} /></div></div>)}</div><p className="mt-5 border-t border-[#EADADD] pt-4 text-xs leading-5 text-[#806C73]">This classifier output is not a diagnosis and does not provide femur or tibia segmentation, medial-meniscus thickness, physical measurements, or implant sizing.</p></section>;
}

function GeminiReportResult({ result, state }: { result: IllustrativeCase["geminiReportResult"]; state: IllustrativeCase["geminiReportState"] }) {
  if (!result) {
    const title = state?.status === "not_a_report" ? "No readable radiology report found" : state?.status === "failed" ? "Report extraction could not complete" : state?.status === "not_configured" ? "Gemini report extraction is not configured" : "No report findings extracted for this case";
    const detail = state?.message ?? "Attach a readable knee radiology report as an image or PDF. Gemini will extract only report-supported findings and explicit measurements for clinician review.";
    return <section className="rounded-[1.6rem] border border-[#EDE3E5] bg-white p-6 shadow-[0_18px_45px_-38px_rgba(92,49,61,0.38)]"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#F3EEF8] text-[#76568A]"><FileImage className="h-5 w-5" /></span><div><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-[#76568A]">Gemini report extraction</p><h3 className="mt-1 text-lg font-extrabold text-[#3E3036]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#806C73]">{detail}</p></div></div></section>;
  }
  const measurements = [
    ["Femoral width", result.femoralWidthMm], ["Femoral AP", result.femoralApMm], ["Tibial width", result.tibialWidthMm], ["Tibial AP", result.tibialApMm],
    ["Meniscus anterior", result.medialMeniscusAnteriorMm], ["Meniscus body", result.medialMeniscusBodyMm], ["Meniscus posterior", result.medialMeniscusPosteriorMm],
  ].filter((item): item is [string, number] => typeof item[1] === "number");
  const findings = [["OA reported", result.oaMention === "reported" ? result.oaSeverity ?? "Reported" : result.oaMention === "not_reported" ? "Not reported" : "Unclear"], ["Femur", result.femurFinding], ["Tibia", result.tibiaFinding], ["Medial meniscus", result.medialMeniscusFinding]].filter((item): item is [string, string] => Boolean(item[1]));
  return <section className="rounded-[1.6rem] border border-[#DDE4EF] bg-[#FAFCFF] p-6 shadow-[0_18px_45px_-38px_rgba(57,77,111,0.32)]"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-[#596F9A]">Gemini report extraction · clinician review</p><h3 className="mt-2 text-xl font-extrabold text-[#35445E]">Report-supported findings</h3><p className="mt-1 text-sm text-[#71809A]">Model: {result.model}</p></div><span className="w-fit rounded-full bg-[#E9EEF8] px-3 py-1.5 text-xs font-extrabold text-[#536A95]">Extracted from report</span></div>{result.summary && <p className="mt-5 rounded-xl border border-[#E1E8F2] bg-white px-4 py-3 text-sm leading-6 text-[#516077]">{result.summary}</p>}<div className="mt-5 grid gap-3 sm:grid-cols-2">{findings.map(([label, value]) => <div key={label} className="rounded-xl border border-[#E1E8F2] bg-white p-4"><p className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-[#7887A0]">{label}</p><p className="mt-2 text-sm font-extrabold leading-5 text-[#42516B]">{value}</p></div>)}</div>{measurements.length > 0 && <div className="mt-5"><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-[#596F9A]">Explicit values written in the report</p><div className="mt-3 grid gap-3 sm:grid-cols-2">{measurements.map(([label, value]) => <div key={label} className="rounded-xl border border-[#DDE4EF] bg-white p-4"><p className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-[#7887A0]">{label}</p><p className="mt-2 text-xl font-extrabold text-[#35445E]">{value.toFixed(1)} mm</p></div>)}</div></div>}<div className="mt-5 rounded-xl border border-[#E1E8F2] bg-white p-4"><p className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-[#7887A0]">Report evidence</p><div className="mt-2 flex flex-wrap gap-2">{result.citedReportPhrases.length ? result.citedReportPhrases.map((phrase) => <span key={phrase} className="rounded-full bg-[#EDF2FA] px-3 py-1.5 text-xs font-semibold text-[#526889]">“{phrase}”</span>) : <span className="text-xs text-[#71809A]">No source phrase returned.</span>}</div><p className="mt-3 text-xs leading-5 text-[#71809A]">{result.reviewNote}</p></div></section>;
}

function GeminiVisualReviewResult({ review, state }: { review: IllustrativeCase["geminiVisualReview"]; state: IllustrativeCase["geminiVisualState"] }) {
  if (!review) {
    const title = state?.status === "not_knee_mri_or_unreadable" ? "Image was not confirmed as a readable knee MRI" : state?.status === "not_an_image" ? "Visual review applies to image studies" : state?.status === "failed" ? "MRI visual review could not complete" : "No MRI visual review for this case";
    return <section className="rounded-[1.6rem] border border-[#E8E0D8] bg-[#FFFCF8] p-6 shadow-[0_18px_45px_-38px_rgba(93,73,48,0.24)]"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#F7E9DC] text-[#9A6A48]"><EyeOff className="h-5 w-5" /></span><div><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-[#9A6A48]">Gemini MRI visual review</p><h3 className="mt-1 text-lg font-extrabold text-[#493B31]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#806F61]">{state?.message ?? "Attach a readable knee MRI image to receive non-calibrated visual descriptors for clinician review."}</p></div></div></section>;
  }
  const structures = [["Femur", review.femur], ["Tibia", review.tibia], ["Medial meniscus", review.medialMeniscus]] as const;
  const qualityLabel = review.imageQuality === "sufficient_for_visual_review" ? "Sufficient for visual review" : review.imageQuality === "limited" ? "Limited visual review" : "Not assessable";
  return <section className="rounded-[1.6rem] border border-[#E8E0D8] bg-[#FFFCF8] p-6 shadow-[0_18px_45px_-38px_rgba(93,73,48,0.24)]"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-[#9A6A48]">Gemini MRI visual review · non-calibrated</p><h3 className="mt-2 text-xl font-extrabold text-[#493B31]">Structure visibility and visual descriptors</h3><p className="mt-1 text-sm text-[#806F61]">{qualityLabel} · {review.model}</p></div><span className="w-fit rounded-full bg-[#F7E9DC] px-3 py-1.5 text-xs font-extrabold text-[#8A5E3E]">No mm estimate</span></div><div className="mt-5 grid gap-3 sm:grid-cols-3">{structures.map(([label, structure]) => <div key={label} className="rounded-xl border border-[#EADFD3] bg-white p-4"><p className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-[#9A806A]">{label}</p><p className="mt-2 text-sm font-extrabold capitalize text-[#493B31]">{structure.visibility.replaceAll("_", " ")}</p><p className="mt-2 text-xs leading-5 text-[#806F61]">{structure.visualDescriptor ?? "No visual descriptor returned."}</p></div>)}</div><p className="mt-5 border-t border-[#EADFD3] pt-4 text-xs leading-5 text-[#806F61]">{review.reviewNote} This output is a visual descriptor only; it is not segmentation and contains no calibrated millimetre measurement.</p></section>;
}

function AnatomyModelBoundary() {
  return <section className="rounded-[1.6rem] border border-[#EDE3E5] bg-white p-6 shadow-[0_18px_45px_-38px_rgba(92,49,61,0.38)]"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#F3EEF8] text-[#76568A]"><CircleAlert className="h-5 w-5" /></span><div><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-[#76568A]">Anatomy measurement model</p><h3 className="mt-1 text-lg font-extrabold text-[#3E3036]">Not included in the supplied model</h3><p className="mt-2 text-sm leading-6 text-[#806C73]">The imported model classifies OA stages only. It has no femur, tibia, or medial-meniscus segmentation masks and no physical-spacing measurement method.</p></div></div><div className="mt-5 divide-y divide-[#F0E7E9] rounded-xl border border-[#EEE3E5] bg-[#FFFCFC] px-4"><p className="flex items-center justify-between py-3 text-sm"><span className="font-extrabold text-[#58454C]">Femur segmentation</span><span className="text-xs font-semibold text-[#927D84]">Requires segmentation model</span></p><p className="flex items-center justify-between py-3 text-sm"><span className="font-extrabold text-[#58454C]">Tibia segmentation</span><span className="text-xs font-semibold text-[#927D84]">Requires segmentation model</span></p><p className="flex items-center justify-between py-3 text-sm"><span className="font-extrabold text-[#58454C]">Medial-meniscus thickness</span><span className="text-xs font-semibold text-[#927D84]">Requires mask + physical spacing</span></p></div></section>;
}

export default function KneeAnalysis() {
  const [, setLocation] = useLocation();
  const [, params] = useRoute("/cases/:caseId/analysis");
  const storedCase = trpc.cases.get.useQuery({ caseReference: params?.caseId ?? "unavailable" });
  const record = storedCase.data ? persistedCaseToWorkspaceCase(storedCase.data) : getIllustrativeCase(params?.caseId);
  const serviceStatus = trpc.analysis.serviceStatus.useQuery();
  const [tab, setTab] = useState<AnalysisTab>("mri");
  const serviceLabel = record.geminiReportResult ? "Report findings available" : record.geminiVisualReview ? "Visual review available" : record.oaClassifierResult ? "Classifier result available" : serviceStatus.isLoading ? "Checking service" : "Awaiting case analysis";

  return <KneeCoAppShell eyebrow="Clinical case" title="Knee Analysis"><div className="mx-auto max-w-7xl"><button type="button" onClick={() => setLocation(`/cases/${record.id}`)} className="mb-5 inline-flex items-center text-sm font-extrabold text-[#8A5563] transition hover:text-[#733963]"><ArrowLeft className="mr-2 h-4 w-4" />Back to Case Detail</button>
    <section className="rounded-[1.75rem] border border-[#EFE4E6] bg-white p-7 shadow-[0_18px_45px_-35px_rgba(92,49,61,0.35)] sm:p-9"><div className="flex flex-col gap-6 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.17em] text-[#A6556A]">AI-assisted review</p><h2 className="font-kneeco-display mt-3 text-4xl tracking-[-0.04em] text-[#352C30]">Knee Analysis</h2><p className="mt-3 text-sm leading-6 text-[#7A676E]">Case {record.id} · {record.patientLabel} · {record.kneeSide} knee</p></div><div className="flex items-center gap-3"><span className="rounded-full bg-[#F8E7EB] px-3 py-2 text-xs font-extrabold text-[#934F60]">{serviceLabel}</span><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#F8E7EB] text-[#A6556A]"><ShieldCheck className="h-5 w-5" /></span></div></div><div className="mt-8 flex w-full overflow-x-auto rounded-xl border border-[#EDE2E5] bg-[#FFFAFB] p-1.5">{tabs.map((item) => <button type="button" key={item.id} onClick={() => setTab(item.id)} className={`min-w-[150px] flex-1 rounded-lg px-4 py-2.5 text-sm font-extrabold transition ${tab === item.id ? "bg-[#733963] text-white shadow-sm" : "text-[#7E686F] hover:bg-white hover:text-[#533F47]"}`}>{item.label}</button>)}</div></section>

    {tab === "mri" && <section className="mt-7 grid gap-7 xl:grid-cols-[minmax(0,1fr)_300px]"><div className="rounded-[1.6rem] border border-[#EDE3E5] bg-white p-5 shadow-[0_18px_45px_-38px_rgba(92,49,61,0.38)] sm:p-6"><div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-[#A6556A]">MRI review</p><h3 className="mt-2 text-xl font-extrabold text-[#3E3036]">Source study</h3></div><div className="flex flex-wrap gap-2"><button type="button" disabled aria-label="Zoom out unavailable until a source image is available" className="rounded-lg border border-[#E6DADD] p-2 text-[#B5A2A7]"><Minus className="h-4 w-4" /></button><button type="button" disabled aria-label="Zoom in unavailable until a source image is available" className="rounded-lg border border-[#E6DADD] p-2 text-[#B5A2A7]"><Plus className="h-4 w-4" /></button><button type="button" disabled aria-label="Reset view unavailable until a source image is available" className="rounded-lg border border-[#E6DADD] p-2 text-[#B5A2A7]"><RotateCcw className="h-4 w-4" /></button><button type="button" disabled aria-label="Expand viewer unavailable until a source image is available" className="rounded-lg border border-[#E6DADD] p-2 text-[#B5A2A7]"><Maximize2 className="h-4 w-4" /></button></div></div><SourceStudyPanel study={record.sourceStudy} onCreateCase={() => setLocation("/new-case")} /></div><aside className="space-y-5"><section className="rounded-[1.6rem] border border-[#EDE3E5] bg-white p-5"><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-[#A6556A]">Structure controls</p><h3 className="mt-2 text-lg font-extrabold text-[#3E3036]">Segmentation unavailable</h3><p className="mt-2 text-xs leading-5 text-[#806C73]">The supplied OA classifier does not include anatomy masks, so structure overlays cannot be generated from it.</p><div className="mt-5 space-y-2"><ToggleRow label="Femur" tone="femur" /><ToggleRow label="Medial meniscus" tone="meniscus" /><ToggleRow label="Tibia" tone="tibia" /></div></section><section className="rounded-[1.6rem] border border-[#EDE3E5] bg-[#FFF9FA] p-5"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#C97C8D] text-white"><Sparkles className="h-4 w-4" /></span><div><p className="text-sm font-extrabold text-[#493940]">Current output</p><p className="mt-0.5 text-xs text-[#806C73]">{record.geminiReportResult ? "Review extracted report findings in Analysis." : record.oaClassifierResult ? "Review the classifier result in Analysis." : "No model or report result is stored for this case."}</p></div></div></section></aside></section>}

    {tab === "measurements" && <section className="mt-7 grid gap-5 lg:grid-cols-2"><OaClassifierResult result={record.oaClassifierResult} /><GeminiReportResult result={record.geminiReportResult} state={record.geminiReportState} /><div className="lg:col-span-2"><GeminiVisualReviewResult review={record.geminiVisualReview} state={record.geminiVisualState} /></div><div className="lg:col-span-2"><AnatomyModelBoundary /></div></section>}

    {tab === "context" && <section className="mt-7 grid gap-5 lg:grid-cols-[.82fr_1.18fr]"><section className="rounded-[1.6rem] border border-[#EDE3E5] bg-white p-6 shadow-[0_18px_45px_-38px_rgba(92,49,61,0.38)]"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#F8E7EB] text-[#A6556A]"><UsersRound className="h-5 w-5" /></span><div><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-[#A6556A]">Patient context</p><h3 className="mt-1 text-lg font-extrabold text-[#3E3036]">Clinical information</h3></div></div><dl className="mt-6 divide-y divide-[#F0E7E9]"><div className="flex items-center justify-between py-3"><dt className="text-sm text-[#806C73]">Age</dt><dd className="text-sm font-extrabold text-[#493940]">{record.age} years</dd></div><div className="flex items-center justify-between py-3"><dt className="text-sm text-[#806C73]">Sex</dt><dd className="text-sm font-extrabold text-[#493940]">{record.sex}</dd></div><div className="flex items-center justify-between py-3"><dt className="text-sm text-[#806C73]">OA status</dt><dd className="text-sm font-extrabold text-[#493940]">{record.oaStatus}</dd></div><div className="flex items-center justify-between py-3"><dt className="text-sm text-[#806C73]">Lifestyle context</dt><dd className="max-w-40 text-right text-sm font-extrabold text-[#493940]">{record.lifestyleContext}</dd></div></dl></section><section className="rounded-[1.6rem] border border-[#EDE3E5] bg-white p-6 shadow-[0_18px_45px_-38px_rgba(92,49,61,0.38)]"><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-[#A6556A]">Reference context</p><h3 className="mt-2 text-xl font-extrabold text-[#3E3036]">Comparison framework</h3><p className="mt-2 max-w-xl text-sm leading-6 text-[#7B676E]">When a validated reference set is configured, reviewed results can be contextualised by age, sex, OA status, and recorded lifestyle information.</p><div className="mt-6 rounded-2xl border border-dashed border-[#DABFC5] bg-[#FFF9FA] p-5"><div className="flex items-start gap-3"><Move className="mt-0.5 h-5 w-5 shrink-0 text-[#A6556A]" /><div><p className="text-sm font-extrabold text-[#503D44]">Reference visualisation</p><p className="mt-1 text-sm leading-6 text-[#806C73]">This area will show a reviewed model output beside a configured reference distribution when validation data is available.</p></div></div></div></section></section>}
  </div></KneeCoAppShell>;
}
