import { KneeCoAppShell } from "@/components/KneeCoAppShell";
import { Button } from "@/components/ui/button";
import { caseDetailPath, closedIllustrativeCases, filterIllustrativeCases } from "@/lib/caseArchive";
import { Archive, ArrowUpRight, CheckCircle2, FileSearch, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { useLocation } from "wouter";

export default function PreviousCases() {
  const [, setLocation] = useLocation();
  const [query, setQuery] = useState("");
  const visibleCases = useMemo(() => filterIllustrativeCases(closedIllustrativeCases, query, "report_signed"), [query]);

  return (
    <KneeCoAppShell eyebrow="Clinical archive" title="Previous Cases">
      <div className="mx-auto max-w-7xl"><section className="rounded-[1.75rem] border border-[#EFE4E6] bg-white p-7 shadow-[0_18px_45px_-35px_rgba(92,49,61,0.35)] sm:p-9"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.17em] text-[#A6556A]">Closed case archive</p><h2 className="font-kneeco-display mt-3 text-4xl tracking-[-0.04em] text-[#352C30] sm:text-5xl">Previous cases</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#7B686F]">Completed cases with clinician-approved reports are retained here for reference and review.</p></div><div className="flex items-center gap-3 rounded-2xl bg-[#FFF5F6] px-4 py-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#C97C8D] text-white"><Archive className="h-4 w-4" /></span><div><p className="text-sm font-extrabold text-[#4C3A41]">{closedIllustrativeCases.length} closed cases</p><p className="mt-0.5 text-xs text-[#846F76]">Reports retained for review</p></div></div></div><label className="relative mt-8 block max-w-xl"><Search className="pointer-events-none absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-[#A28C92]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search a closed case or patient" className="h-11 w-full rounded-xl border border-[#E8DDDF] bg-white pl-10 pr-4 text-sm font-semibold text-[#4A3A40] outline-none placeholder:text-[#B19DA3] focus:ring-2 focus:ring-[#C97C8D]" /></label></section>

        <section className="mt-7 overflow-hidden rounded-[1.6rem] border border-[#EDE3E5] bg-white shadow-[0_18px_45px_-38px_rgba(92,49,61,0.38)]"><div className="flex flex-col gap-3 border-b border-[#F0E7E9] p-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-[#A6556A]">Report archive</p><h3 className="mt-2 text-xl font-extrabold text-[#403239]">{visibleCases.length} closed case{visibleCases.length === 1 ? "" : "s"}</h3></div><p className="text-sm text-[#8A747B]">Open a case to review its approved record.</p></div><div className="hidden grid-cols-[1.05fr_.75fr_.4fr_.55fr_.75fr_.8fr_.75fr] gap-4 border-b border-[#F0E7E9] bg-[#FFFAFB] px-6 py-3 text-[10px] font-extrabold uppercase tracking-[0.13em] text-[#9D868D] md:grid"><span>Case</span><span>Patient</span><span>Age</span><span>Knee</span><span>OA</span><span>Report</span><span>Closed</span></div>{visibleCases.length ? visibleCases.map((record) => <button type="button" key={record.id} onClick={() => setLocation(caseDetailPath(record.id))} className="grid w-full gap-3 border-b border-[#F3EAEC] px-6 py-5 text-left transition last:border-0 hover:bg-[#FFF9FA] md:grid-cols-[1.05fr_.75fr_.4fr_.55fr_.75fr_.8fr_.75fr] md:items-center md:gap-4"><div><p className="text-sm font-extrabold text-[#43343A]">{record.id}</p><p className="mt-1 text-xs text-[#987F87]">{record.sex}</p></div><p className="text-sm font-semibold text-[#5C484F]">{record.patientLabel.replace("Patient ", "")}</p><p className="text-sm text-[#755F67]">{record.age}</p><p className="text-sm text-[#755F67]">{record.kneeSide}</p><p className="text-sm text-[#755F67]">{record.oaStatus}</p><span className="flex w-fit items-center gap-1.5 rounded-full bg-[#E8F4EF] px-2.5 py-1 text-[11px] font-extrabold text-[#2D7A58]"><CheckCircle2 className="h-3.5 w-3.5" />Signed</span><span className="flex items-center gap-1 text-xs font-extrabold text-[#896D75]">{record.updatedAt}<ArrowUpRight className="h-3.5 w-3.5" /></span></button>) : <div className="flex min-h-52 flex-col items-center justify-center p-8 text-center"><FileSearch className="h-6 w-6 text-[#B78691]" /><p className="mt-3 text-sm font-extrabold text-[#4A393F]">No matching closed cases</p><p className="mt-1 text-sm text-[#88727A]">Try another patient or case ID.</p></div>}</section>
      </div>
    </KneeCoAppShell>
  );
}
